[package]
name = "sc-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.35.0"
sc-prelude = {path = "../prelude"}
sc-game ={ path = "../game" }
sc-render ={ path = "../render" }