[package]
name = "sc-plugin-bindings"
version = "1.0.0"
edition = "2018"

[dependencies]
fp-bindgen-support = { version = "3.0.0", features = ["guest"] }
once_cell = { version = "1" }
rmp-serde = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
