[package]
name = "world-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prelude = {path = "../prelude"}
core-obj = {path = "../core-obj"}
oneshot = "0.1.6"
