[package]
name = "world-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prelude = {path = "../prelude"}
rstest = "0.18.2"
world-protocol = {path = "../world-protocol"}
core-obj = { path = "../core-obj"}
rayon = "1.8.0"
flume = "0.11.0"
vector3d = "0.2.1"
rustc-hash = "1.1.0"
parking_lot = "0.12.1"
