[package]
name = "sc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc-prelude = { path = "../prelude" }

[dev-dependencies]
rstest = "0.18.1"
